name: Run Tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest # Will use Ubuntu 22.04 or 20.04

    strategy:
      matrix:
        python-version: ["3.8.18", "3.9.18", "3.10.13", "3.11.9"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] || pip install -e .
          pip install pytest

      - name: Run tests
        run: pytest
